### ISSUE TITLE
User-ID

### ISSUE THREAD

**Issue by andrasbari** [escopecz/grav-ganalytics#17]
In the Google Search Console there is an extra option, which called User-ID.
It can be used with:
`ga('set', 'userId', 'USER_ID');`

**Comment by escopecz** [comment]
I don't follow.

**Comment by ViliusS** [comment]
@andrasbari User-ID must be unique and persistent for every identifiable user on the system. Implementation of this is difficult and could be very well out of scope of this plugin.

Since Grav is usually used on public facing websites which do not identify their users, unless somebody is willing to provide a patch, I don't think support for User-ID could happen any time soon.
